url: https://oakworks.github.io
baseurl: ""

# Site settings
title: Oak.Works
email: team@oak.works
description: "Oak Works is a full stack develpoment shop. When we say 'full stack', we mean that we help you do everything right. From the front of your site to the backend database, from the first twinkle of an idea in your eye to your billionth customer. We help you grow smart and we're in it with our customers for the long haul."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Rob Lingle
  pic: //lh3.googleusercontent.com/-I31Q_k5g-54/AAAAAAAAAAI/AAAAAAAAACA/kTILRZHpNCQ/s120-c/photo.jpg
  position: Founder
  social:
    - title: github
      url: https://github.com/roblingle
    - title: twitter
      url: https://twitter.com/roblingle
    - title: stack-overflow
      url: http://stackoverflow.com/users/2747869/roblingle
    - title: linkedin
      url: https://www.linkedin.com/in/roblingle

- name: Steve Ross
  pic: //lh4.googleusercontent.com/-dhJVPb1wIn4/AAAAAAAAAAI/AAAAAAAAACo/guSBOBki8Rg/s120-c/photo.jpg
  position: Founder
  social:
    - title: github
      url: https://github.com/steve-ross
    - title: twitter
      url: https://twitter.com/steve__ross
    - title: stack-overflow
      url: http://stackoverflow.com/users/92176/steve-ross
    - title: linkedin
      url: https://www.linkedin.com/in/stevesross

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/theoakworks
  - title: facebook
    url: http://facebook.com/theoakworks
  - title: github
    url: http://github.com/oakworks

# Postal address (add as many lines as necessary)
address:
  - line: 415 W Boundary St
  - line: Savannah, GA 31405

# Build settings
markdown: kramdown
permalink: pretty
