url: https://oakworks.github.io
baseurl: ""
timezone: America/New_York

# Site settings
title: Oak.Works
email: team@oak.works
description: "Oak Works is a full stack develpoment shop. When we say 'full stack', we mean that we help you do everything right. From the front of your site to the backend database, from the first twinkle of an idea in your eye to your billionth customer. We help you grow smart and we're in it with our customers for the long haul."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
  paragraph-link: 565656

# Team names, titles and social links
people:
- name: Rob Lingle
  pic: //lh3.googleusercontent.com/-I31Q_k5g-54/AAAAAAAAAAI/AAAAAAAAACA/kTILRZHpNCQ/s120-c/photo.jpg
  position: Founder
  bio: "Rob is on a quest to simplify things. After graduating from Georgia Tech with a degree in Computer Engineering, he decided he'd rather play with computers than build them. So he moved into software development. There he spent most of the last decade-plus turning error-prone, paper-form-heavy processes into web applications that improve awareness and communication. And those are things Rob's really into."
  social:
    - title: github
      url: https://github.com/roblingle
    - title: twitter
      url: https://twitter.com/roblingle
    - title: stack-overflow
      url: http://stackoverflow.com/users/2747869/roblingle
    - title: linkedin
      url: https://www.linkedin.com/in/roblingle

- name: Steve Ross
  pic: //lh4.googleusercontent.com/-dhJVPb1wIn4/AAAAAAAAAAI/AAAAAAAAACo/guSBOBki8Rg/s120-c/photo.jpg
  position: Founder
  bio: "It was the mid 90s, Steve was an intern and his supervisor remarked “we are building a website and you know computer stuff.” Fast forward 18 years through an animation degree, a brief stint as a creative director, an interactive designer for a .com during the bubble, and a UX/UI position which led to a transition to software development. Steve loves solving problems through code and still maintains a love of all things UX (and kiteboarding)."
  social:
    - title: github
      url: https://github.com/steve-ross
    - title: twitter
      url: https://twitter.com/thesteveross
    - title: stack-overflow
      url: http://stackoverflow.com/users/92176/steve-ross
    - title: linkedin
      url: https://www.linkedin.com/in/stevesross

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/theoakworks
  - title: facebook
    url: http://facebook.com/theoakworks
  - title: github
    url: http://github.com/oakworks

# Postal address (add as many lines as necessary)
address:
  - line: 415 W Boundary St
  - line: Savannah, GA 31405

# Build settings
markdown: kramdown
permalink: pretty
