url: https://oak.works
baseurl: ""
timezone: America/New_York

# Site settings
title: Oak.Works, Strategy + Development.
email: team@oak.works
description: "Strategy first software. We start by understanding your product before we write one line of code. Let's grow your business together."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
  paragraph-link: 565656

# Team names, titles and social links
people:
- name: Rob Lingle
  pic: //lh3.googleusercontent.com/-I31Q_k5g-54/AAAAAAAAAAI/AAAAAAAAACA/kTILRZHpNCQ/s120-c/photo.jpg
  position: Founder
  bio: "Rob is on a quest to simplify things. After graduating from Georgia Tech with a degree in Computer Engineering, he decided he'd rather play with computers than build them. So he moved into software development. There he spent most of the last decade-plus turning error-prone, paper-form-heavy processes into web applications that improve awareness and communication. And those are things Rob's really into."
  social:
    - title: github
      url: https://github.com/roblingle
    - title: twitter
      url: https://twitter.com/roblingle
    - title: stack-overflow
      url: http://stackoverflow.com/users/2747869/roblingle
    - title: linkedin
      url: https://www.linkedin.com/in/roblingle

- name: Steve Ross
  pic: //lh4.googleusercontent.com/-dhJVPb1wIn4/AAAAAAAAAAI/AAAAAAAAACo/guSBOBki8Rg/s120-c/photo.jpg
  position: Founder
  bio: "It was the mid 90s, Steve was an intern and his supervisor remarked “we are building a website and you know computer stuff.” Fast forward 18 years through an animation degree, a brief stint as a creative director, an interactive designer for a .com during the bubble, and a UX/UI position which led to a transition to software development. Steve loves solving problems through code and still maintains a love of all things UX (and kiteboarding)."
  social:
    - title: github
      url: https://github.com/steve-ross
    - title: twitter
      url: https://twitter.com/thesteveross
    - title: stack-overflow
      url: http://stackoverflow.com/users/92176/steve-ross
    - title: linkedin
      url: https://www.linkedin.com/in/stevesross

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/theoakworks
  - title: facebook
    url: http://facebook.com/theoakworks
  - title: github
    url: http://github.com/oakworks

# Postal address (add as many lines as necessary)
address:
  - line: 415 W Boundary St
  - line: Savannah, GA 31405

# minor projects
miniprojects:
# - title: US Army Special Operations Command
#   description: Created an application to streamline multiple processes for requesting, prioritizing, planning and budgeting military construction and facility maintenance. Used by engineers and planners around the globe to coordinate more effectively.
#   icon: fa-users
#   url: http://www.soc.mil

- title: Merchantry
  description: Designed, Developed and Deployed a Magento extension which fully integrates the Merchantry platform into any Magento store. This allows the store owner to sell Merchantry partner products or syndicate their own products into the Merchantry platform.
  icon: fa-shopping-cart
  url: http://merchantry.com

# - title: Dealer Tire
#   description: Helped design and upgrade their platform. Worked as part of a team to develop a set of services and APIs to improve business-to-business operations. Helped develop the consumer-facing RightTurn.com.
#   icon: fa-car
#   url: http://dealertire.com

- title: KeatonRow
  description: Wrote a tool to import and synchronize products, images, pricing, and more from retialers such as Nordstrom, Asos, Shopbop, Les Nouvelles, and more using NodeJS.
  icon: fa-tasks
  url: http://keatonrow.com

# - title: Gauge Interactive
#   description: Consultant on various projects including integrations with Magento, SalesForce, raw MySQL exports, debugging and server tuning.
#   icon: fa-code
#   url: http://gaugeinteractive.com

- title: BellaBag
  description: Wrote a tool to export their Magento products to Polyvore and Google Shopping on a scheduled basis. Implemented and Migrated email from GoDaddy to Google Apps. Increased site performance by implementing CloudFlare.
  icon: fa-plug
  url: http://bellabag.com



# Build settings
markdown: kramdown
permalink: pretty
